SELECT      *
FROM  OPENQUERY (R7DBARPT,'
SELECT SUBSTR(PBI.PROBLEM_INVESTIGATION_ID,1,15) "PBI"
,SUBSTR(PBI.DESCRIPTION,1,100) "Summary"
,TO_CHAR((FROM_TZ(CAST((TO_DATE(''19700101000000'',''YYYYMMDDHH24MISS'') + NUMTODSINTERVAL(PBI.SUBMIT_DATE,''SECOND'')) AS TIMESTAMP),''GMT'') AT TIME ZONE ''Singapore''), ''YYYY-MM-DD HH24:MI'') "DateSubmitted"
,TO_CHAR((FROM_TZ(CAST((TO_DATE(''19700101000000'',''YYYYMMDDHH24MISS'') + NUMTODSINTERVAL(PBI.LAST_MODIFIED_DATE,''SECOND'')) AS TIMESTAMP),''GMT'') AT TIME ZONE ''Singapore''), ''YYYY-MM-DD HH24:MI'') "DateLastModified"
,DECODE(PBI.INVESTIGATION_STATUS ,0,''Draft'' ,1,''Under Review'' ,2,''Req For Auth'' ,3,''Assigned'' ,4,''Under Inves'' ,5,''Pending'' ,6,''Completed'' ,7,''Rejected'' ,8,''Closed'' ,9,''Cancelled'' ,PBI.INVESTIGATION_STATUS) "Status"
,SUBSTR(PBI.ASSIGNED_GROUP,1,30) "AssignedGroup"
,SUBSTR(PBI.ASSIGNEE,1,20) "AssignedTo"
,SUBSTR(PBI.ASSIGNEE_PBLM_MGR,1,30) "Coordinator"
,SUBSTR(TAS.TASK_ID,1,15) "TAS"
,SUBSTR(TAS.SUMMARY,1,100) "TASSummary"
,TO_CHAR((FROM_TZ(CAST((TO_DATE(''19700101000000'',''YYYYMMDDHH24MISS'') + NUMTODSINTERVAL(TAS.CREATE_DATE,''SECOND'')) AS TIMESTAMP),''GMT'') AT TIME ZONE ''Singapore''), ''YYYY-MM-DD HH24:MI'') "TASDateSubmitted"
,TO_CHAR((FROM_TZ(CAST((TO_DATE(''19700101000000'',''YYYYMMDDHH24MISS'') + NUMTODSINTERVAL(TAS.MODIFIED_DATE,''SECOND'')) AS TIMESTAMP),''GMT'') AT TIME ZONE ''Singapore''), ''YYYY-MM-DD HH24:MI'') "TASDateLastModified"
,DECODE(TAS.STATUS ,1000,''Staged'' ,2000,''Assigned'' ,3000,''Pending'' ,4000,''In Progress'' ,5000,''Waiting'' ,6000,''Closed'' ,7000,''Bypassed'' ,TAS.STATUS) "TASStatus"
,SUBSTR(TAS.ASSIGNEE,1,20) "TASAssignedTo"
,SUBSTR(TAS.LAST_MODIFIED_BY,1,8) "TASLastModified"
,SUBSTR(TAS.SUBMITTER,1,8) "TASSubmitter"
FROM ARADMIN.TMS_TASK TAS
INNER JOIN ARADMIN.PBM_PROBLEM_INVESTIGATION PBI ON TAS.ROOTREQUESTID=PBI.PROBLEM_INVESTIGATION_ID 
WHERE PBI.PROBLEM_INVESTIGATION_ID=''PBI000000040450''
ORDER BY TAS.STATUS
')



