
create table #temp_R7DBARTP
(
   ServerName varchar(100),
   DBName varchar(100),
   Role varchar(50),
   GroupName varchar(200)
)

INSERT INTO #temp_R7DBARTP
SELECT * FROM OPENQUERY (R7DBARPT,'
select DISTINCT SUBSTR(SVR.NAME,1,40) "ServerName"
,SUBSTR(DB.NAME,1,80) "DBName"
,SUBSTR(FV.VALUE,1,12) "Role"
,SUBSTR(PPL.FULL_NAME,1,65) "GroupName"
from ARADMIN.AST_DATABASE DB
inner join ARADMIN.BMC_CORE_BMC_BASERELATIONSHIP REL on DB.INSTANCE_ID=REL.DESTINATION_INSTANCEID AND (REL.MARKASDELETED=0 OR REL.MARKASDELETED IS NULL)
inner join ARADMIN.AST_DATABASE SVR on REL.SOURCE_INSTANCEID=SVR.INSTANCE_ID
left join ARADMIN.AST_ASSETPEOPLE PPL ON DB.RECONCILIATION_IDENTITY=PPL.ASSETINSTANCEID
left join ARADMIN.FIELD_ENUM_VALUES FV ON PPL.PERSONROLE=FV.ENUMID and FV.SCHEMAID=1340 and FV.FIELDID=260100005
where SVR.COST_CENTER = ''SQLAAS''
order by "ServerName", "DBName"
')

SELECT * FROM #temp_R7DBARTP
where ServerName in ('NTSYDDBP324V2\M324CPRD02','NTSYDDBP324V3\M324CPRD03','NTSYDDBP324V4\M324CPRD04')
and (GroupName <> 'Macquarie Group->ITG ITS->DBA Operations-Global' or GroupName IS NULL)
--and role = 'Supported by'
order by 1,2


drop table #temp_R7DBARTP
